### ISSUE TITLE
Unable to Build the Solution

### ISSUE THREAD

**Issue by jajanps** [nhibernate/NHibernate.AspNet.Identity#41]
Hi,

I get the following build error after restoring all packages using nuget restore. It doesn't redirects to a line or anything.

Error : 

"Error occurred: System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at GitVersion.ConfigurationProvider.GetConfigFilePath(String gitDirectory) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\Configuration\ConfigurationProvider.cs:line 51
   at GitVersion.ConfigurationProvider.Provide(String gitDirectory, IFileSystem fileSystem) in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionCore\Configuration\ConfigurationProvider.cs:line 13
   at GitVersionTask.WriteVersionInfoToBuildLog.InnerExecute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 54
   at GitVersionTask.WriteVersionInfoToBuildLog.Execute() in c:\BuildAgent\work\68ea6bfb44e5afb\GitVersionTask\WriteVersionInfoToBuildLog.cs:line 31	NHibernate.AspNet.Identity
" 

Can you guys please help me out with this one.

**Comment by milesibastos** [comment]
run: nuget restore source\NHibernate.AspNet.Identity.sln
like on: https://ci.appveyor.com/project/milesibastos/nhibernate-aspnet-identity/build/2.2.2%20(Build%2023)
maybe fix the problem if u have a problem with nuget restore by IDE

**Comment by marcdrexel** [comment]
@jajanps 
just remove GitVersionTask with the NuGet-Package Manager or install the git client and get the project via git clone

**Comment by milesibastos** [comment]
@jajanps, @marcdrexel 
I think this is closed!
Please, open a new one if not.

**Comment by tpilat** [comment]
solution > Manage NuGet Packages for Solution > find GitVersionTask > update to last stable version for all Projects in solution (if needed)
